#!/bin/sh

echo 'Création de la base de données de test...'

echo 'Création des élèves...\n'

curl -d "lastname=Durel&firstname=Enzo" -X POST "http://localhost:8081/eleves/create"
curl -d "lastname=Perdu&firstname=Timothé" -X POST "http://localhost:8081/eleves/create"
curl -d "lastname=Lefou&firstname=Georges" -X POST "http://localhost:8081/eleves/create"

echo '\n\nCréation des professeurs...\n'

curl -d "lastname=Cest&firstname=Bastien&username=cebastien&password=1234" -X POST "http://localhost:8081/professeurs/create"
curl -d "lastname=Sarah&firstname=Croche&username=sacroche&password=1234" -X POST "http://localhost:8081/professeurs/create"
curl -d "lastname=Barack&firstname=Obama&username=baobama&password=1234" -X POST "http://localhost:8081/professeurs/create"

echo '\n\nCréation des gommettes...\n'

curl -d "color=BLEU&description=Devoirs non faits" -X POST "http://localhost:8081/gommettes/create"
curl -d "color=ROUGE&description=Bavardages" -X POST "http://localhost:8081/gommettes/create"
curl -d "color=BLANC&description=Service à la communauté" -X POST "http://localhost:8081/gommettes/create"

echo '\n\nAttribution des gommettes...\n'

curl -d "id_student=1&id_prof=1&id_gommette=3&date=13/04/2022&behavior=Il a taclé un aveugle" -X POST "http://localhost:8081/gommettesAttribuees/create"
curl -d "id_student=2&id_prof=3&id_gommette=2&date=11/03/2022&behavior=Il a parlé en langue des signes avec son camarade, ça m'a rendu fou !" -X POST "http://localhost:8081/gommettesAttribuees/create"
curl -d "id_student=2&id_prof=2&id_gommette=1&date=12/04/2022&behavior=Il a mangé son cahier de textes" -X POST "http://localhost:8081/gommettesAttribuees/create"

echo '\n\nTerminé'
