#!/bin/sh

echo 'Création de la base de données de test...'

echo 'Création des élèves...'

curl -d "lastname=Durel&firstname=Enzo" -X POST "http://localhost:8081/eleves/create"
curl -d "lastname=Perdu&firstname=Timothé" -X POST "http://localhost:8081/eleves/create"
curl -d "lastname=Lefou&firstname=Georges" -X POST "http://localhost:8081/eleves/create"

echo 'Création des professeurs...'

curl -d "lastname=Cest&firstname=Bastien&username=cebastien&password=1234" -X POST "http://localhost:8081/professeurs/create"
curl -d "lastname=Sarah&firstname=Croche&username=sacroche&password=1234" -X POST "http://localhost:8081/professeurs/create"
curl -d "lastname=Barack&firstname=Obama&username=baobama&password=1234" -X POST "http://localhost:8081/professeurs/create"

echo 'Création des gommettes...'

curl -d "color=vert&description=Devoirs non faits" -X POST "http://localhost:8081/gommettes/create"
curl -d "color=rouge&description=Bavardages" -X POST "http://localhost:8081/gommettes/create"
curl -d "color=blanc&description=Service à la communauté" -X POST "http://localhost:8081/gommettes/create"

echo 'Terminé'
